housing/config/routes.rb
Housing::Application.routes.draw do
  resources :reviews

 get ':action' => 'static_content#:action'

  root :to => 'static_content#home'

end

housing/app/models/review.rb
class Review < ActiveRecord::Base
end

housing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

housing/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:facility, :current, :year, :title_your_review, :pros, :cons, :suggestions, :score)
    end
end

housing/app/controllers/static_content_controller.rb
class StaticContentController < ApplicationController
  def home
# sign-in ActiveAdmin logic here
    #if user_signed_in?
      #redirect_to reviews_path
    #else
#      ?
#    end
  end

  def about
  end

  def faq
  end

  def privacy
  end

  def tos
  end
end

housing/app/helpers/application_helper.rb
module ApplicationHelper
end

housing/app/helpers/reviews_helper.rb
module ReviewsHelper
end

housing/app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="clearfix">
      <ul class="list-inline pull-left">
        <li><%= link_to "About", "/about" %></li>
        <li><%= link_to "FAQ", "/faq" %></li>
        <li><%= link_to "Terms of Service", "/tos" %></li>
        <li><%= link_to "Privacy Policy", "/privacy" %></li>
      </ul>

      <ul class="list-inline pull-right">
        <li><%= link_to "Twitter", "https://twitter.com/GoldenGuide" %></li>
        <li><%= link_to "Facebook", "https://www.facebook.com/pages/GoldenGuide/221118768011086" %></li>
        <li><%= link_to "LinkedIn", "http://www.linkedin.com/company/goldenguide" %></li>
      </ul>
    </div>

    <p>Copyright 2015 GoldenGuide, LLC. All rights reserved. </p>

  </div>
</div>

housing/app/views/layouts/_header.html.erb
<nav id="header" class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "GoldenGuide", root_path, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <%= nav_link_to "Find Housing", housings_path %>
      <%= nav_link_to "Reviews", reviews_path %>
      <!  enter search box   -->

      <%= nav_link_to "Reviews", reviews_path %>

      <! - % if user_signed_in? %> <! save this for another day -->
      <%= nav_link_to "Give a Review", create_reviews_path %>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown signed-in">
          <%= link_to "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" do %>
            <%= current_user.name %>

            <b class="caret"></b>
          <% end %>

          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>

            <li class="divider"></li>

            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
          </ul>
        </li>
      <% else %>
        <li class="dropdown">
          <%= link_to "Sign up / Sign in", "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" %>

          <ul class="dropdown-menu">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>

            <li class="divider"></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

housing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SeniorHousing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<body>

<%= yield %>


<%= render :partial => "layouts/footer" %>

</body>
</html>

housing/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :facility %><br>
    <%= f.text_field :facility %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.check_box :current %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :title_your_review %><br>
    <%= f.text_field :title_your_review %>
  </div>
  <div class="field">
    <%= f.label :pros %><br>
    <%= f.text_field :pros %>
  </div>
  <div class="field">
    <%= f.label :cons %><br>
    <%= f.text_area :cons %>
  </div>
  <div class="field">
    <%= f.label :suggestions %><br>
    <%= f.text_field :suggestions %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

housing/app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

housing/app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Facility</th>
      <th>Current</th>
      <th>Year</th>
      <th>Title your review</th>
      <th>Pros</th>
      <th>Cons</th>
      <th>Suggestions</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.facility %></td>
        <td><%= review.current %></td>
        <td><%= review.year %></td>
        <td><%= review.title_your_review %></td>
        <td><%= review.pros %></td>
        <td><%= review.cons %></td>
        <td><%= review.suggestions %></td>
        <td><%= review.score %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

housing/app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

housing/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Facility:</strong>
  <%= @review.facility %>
</p>

<p>
  <strong>Current:</strong>
  <%= @review.current %>
</p>

<p>
  <strong>Year:</strong>
  <%= @review.year %>
</p>

<p>
  <strong>Title your review:</strong>
  <%= @review.title_your_review %>
</p>

<p>
  <strong>Pros:</strong>
  <%= @review.pros %>
</p>

<p>
  <strong>Cons:</strong>
  <%= @review.cons %>
</p>

<p>
  <strong>Suggestions:</strong>
  <%= @review.suggestions %>
</p>

<p>
  <strong>Score:</strong>
  <%= @review.score %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

housing/app/views/static_content/about.html.erb
<div class='about'>
  <div class='hero-unit'>
    <h3>Golden Guide: Your compass through the senior housing maze.</h3>

    <p>Find all the senior housing information you need to help make the right choice for you or your loved ones!</p>

    <ul>Search for senior housing by criteria such as location, services provided,cost and ratings.</p>
    <p>Users can easily see ratings from city, state and federal government.
    <p>Members can contribute a review.</p></ul>

    <p>Golden Guide is headquartered in Seattle, WA.
  </div>

housing/app/views/static_content/faq.html.erb
<h3>FAQ</h3>
<p>FAQ1</p>
<p>FAQ2</p>